### ISSUE TITLE
Remove application.properties from git

### ISSUE THREAD

**Issue by MontealegreLuis** [TEWO-Capstone/TEWO#8]
Hi team, `application.properties` should not be added to git, it might contain sensitive information like passwords or API keys that we do not want to share with others. At this point it is not a big issue because it contains local development information. Please remove it when you have some time.

**Comment by washingtondnavarro** [comment]
Thank you. We add the line "src/main/resources/application.properties" to our git ignore.

**Comment by MontealegreLuis** [comment]
Great! But you also need to delete the file and commit that deletion I still see the file in your master branch

https://github.com/TEWO-Capstone/TEWO/blob/master/src/main/resources/application.properties

**Comment by jcandia2** [comment]
ok done. Thank you Sir.
